### ISSUE TITLE
another nonparsing uri

### ISSUE THREAD

**Issue by emckean** [metoikos/hapi-multi-mongo#4]
Hi! I found another valid uri format that doesn't quite match the regex. :( Have you looked at maybe using [parse-mongo-url](https://github.com/sorribas/parse-mongo-url/blob/master/index.js)? It seems to handle all the variants and there's a pull request right now to handle '+srv' uris.

**Comment by metoikos** [comment]
Hi @emckean.

So I think I should separate the connection uri parser and add more tests for all kind of edge cases. I'll check your suggestion and there is also this [mongodb-core uri_parser.js](https://github.com/mongodb-js/mongodb-core/blob/master/lib/uri_parser.js) which is official uri parser for mongo. I'll check both then try to implement one of them.

Thank you for your suggestions. Go Regex  :)

**Comment by metoikos** [comment]
Well, to get rid off of all this regex burden, I replaced uri parsing mechanism with mongodb-core's uri parser and  it also validates connection options.

Removed bluebird dependency and did some make-up in code.

Thanks again to bring that all up
[Fixed](https://github.com/metoikos/hapi-multi-mongo/commit/e633c41486a470a831c3349f8e138c48f8b444bb)

**Comment by emckean** [comment]
That's awesome! Thank you!
